const layers={
 sense:{kicker:'SENSOR PLANE',title:'Time-aligned, calibrated observations',copy:'A synchronized RGB/stereo pair supplies texture and depth; LiDAR or solid-state depth provides geometric redundancy; GNSS/RTK, barometer and IMU anchor every observation in time and space.',items:['Global-shutter stereo camera','Optional 3D LiDAR or depth camera','GNSS/RTK + IMU + barometer','Hardware timestamps and calibration']},
 perceive:{kicker:'EDGE PERCEPTION',title:'Objects, surfaces and motion—with uncertainty',copy:'GPU-accelerated nodes turn images into tracks, depth and semantic masks. Every output carries a timestamp and confidence so stale or ambiguous evidence can be rejected.',items:['Detection and multi-object tracking','Stereo depth and visual-inertial odometry','Road/free-space segmentation','TensorRT-optimized inference']},
 reason:{kicker:'AUTONOMY LAYER',title:'Fuse locally, plan within firm limits',copy:'A local map combines perception with vehicle and drone state. The planner proposes bounded paths inside geofences while a supervisor monitors health, clearance and energy reserves.',items:['ROS 2 transforms and sensor fusion','Rolling occupancy and elevation maps','Risk-aware local route planner','Geofence, battery and link monitors']},
 act:{kicker:'CONTROL + INTERFACE',title:'Keep flight control deterministic and vehicle access bounded',copy:'PX4 owns stabilization and failsafes. The companion requests high-level motion and publishes signed hazard events to a vehicle-side safety gateway—never directly to actuation buses.',items:['PX4 position/trajectory setpoints','Independent return and controlled-land behavior','Authenticated, freshness-checked events','Advisory-only vehicle output in v1']}
};
document.querySelectorAll('.node').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.node').forEach(n=>n.classList.remove('active'));btn.classList.add('active');const d=layers[btn.dataset.layer];document.querySelector('#layer-kicker').textContent=d.kicker;document.querySelector('#layer-title').textContent=d.title;document.querySelector('#layer-copy').textContent=d.copy;document.querySelector('#layer-list').innerHTML=d.items.map(x=>`<li>${x}</li>`).join('')}));
const menu=document.querySelector('.menu'),nav=document.querySelector('#nav-links');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
addEventListener('scroll',()=>document.querySelector('.nav').classList.toggle('scrolled',scrollY>30),{passive:true});
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.15});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('#year').textContent=new Date().getFullYear();
